[workspace]
members = ["pcpproxy", "peercastoxide-lib", "peercastoxide-server"]
exclude = ["pcpproxy_gui"]
resolver = "2"

[workspace.dependencies]
peercastoxide-lib = { path = "peercastoxide-lib" }
tracing = { version = "0.1.40", features = ["attributes"] }
